# Generated manually for Phase 1 skeleton
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="Genre", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("tmdb_id", models.PositiveIntegerField(blank=True, null=True, unique=True)), ("name", models.CharField(max_length=80, unique=True))]),
        migrations.CreateModel(name="Person", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("tmdb_id", models.PositiveIntegerField(blank=True, null=True, unique=True)), ("name", models.CharField(max_length=255)), ("profile_path", models.CharField(blank=True, max_length=255))]),
        migrations.CreateModel(name="Title", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("type", models.CharField(choices=[("movie", "Movie"), ("tv", "TV Show")], max_length=10)), ("tmdb_id", models.PositiveIntegerField()), ("tvmaze_id", models.PositiveIntegerField(blank=True, null=True)), ("imdb_id", models.CharField(blank=True, max_length=30)), ("title", models.CharField(max_length=255)), ("original_title", models.CharField(blank=True, max_length=255)), ("overview", models.TextField(blank=True)), ("poster_path", models.CharField(blank=True, max_length=255)), ("backdrop_path", models.CharField(blank=True, max_length=255)), ("release_date", models.DateField(blank=True, null=True)), ("first_air_date", models.DateField(blank=True, null=True)), ("source_status", models.CharField(blank=True, max_length=80)), ("runtime", models.PositiveIntegerField(blank=True, null=True)), ("created_at", models.DateTimeField(default=django.utils.timezone.now)), ("updated_at", models.DateTimeField(auto_now=True)), ("genres", models.ManyToManyField(blank=True, to="catalog.genre"))], options={"unique_together": {("type", "tmdb_id")}}),
        migrations.CreateModel(name="Season", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("season_number", models.PositiveIntegerField()), ("name", models.CharField(blank=True, max_length=255)), ("overview", models.TextField(blank=True)), ("air_date", models.DateField(blank=True, null=True)), ("title", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="seasons", to="catalog.title"))], options={"unique_together": {("title", "season_number")}}),
        migrations.CreateModel(name="Episode", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("episode_number", models.PositiveIntegerField()), ("name", models.CharField(max_length=255)), ("overview", models.TextField(blank=True)), ("air_date", models.DateField(blank=True, null=True)), ("season", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="episodes", to="catalog.season"))], options={"unique_together": {("season", "episode_number")}}),
        migrations.CreateModel(name="CastCredit", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("character", models.CharField(blank=True, max_length=255)), ("order", models.PositiveIntegerField(default=0)), ("person", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cast_credits", to="catalog.person")), ("title", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cast_credits", to="catalog.title"))], options={"ordering": ["order"]}),
    ]
